#!/bin/bash -e

# plots the evaluation results
#
# uses the train??.onsets.fixedparam.eval files, which are generated by 'run_eval.sh'


{

  for file in train??.onsets.fixedparam.eval; do
awk -v fni=$file -f - $file <<"EOF"

NR > 1 { 
  data = data " " $7
}

END {
  file = substr(fni, 6,2);
  print sprintf("%d", file) data
}
EOF
done

}  > fixed_grouped_by_file.eval


{

  gnuplot -p <<"EOF"
set terminal png size 1024,768
set style data histogram
set title "F-Measure for every algorithm grouped by file, fixed parameters"
set style histogram clustered gap 4

set boxwidth 0.9
set style fill solid 
set datafile missing "-"
set yrange [0:1]

plot for [i=2:11] "fixed_grouped_by_file.eval" u i t ""

EOF

} > fixedparam_by_file.png



